config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/update'
  get 'comments/destroy'
  get 'comments/index'
  get 'recipes/index'
  get 'recipes/destroy'
  get 'recipes/update'
  get 'recipes/create'
  get 'recipes/show'
  resources :items
  resources :recipes
  resources :comments
  resources :recipe_comments
  get '/recipes/:id/toggle_current', to: 'recipes#toggle_current', as: 'toggle_current_recipe'
  post '/items/:id/mark', to: 'items#mark', as: 'mark_item'
  post '/items/delete_all', to: 'items#delete_all', as: 'delete_all'
  post '/items/delete_all_marked', to: 'items#delete_all_marked', as: 'delete_all_marked'
  post 'recipes/delete_all', to: 'recipes#delete_all', as: 'delete_all_recipes'
  devise_for :users
  root to: 'pages#home'
  mount API::Base, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_comments, dependent: :destroy
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Items
      mount API::V1::Recipes
    end
  end
end

app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix "api"
        version "v1", using: :path
        default_format :json
        format :json
        formatter :json, 
             Grape::Formatter::ActiveModelSerializers

        helpers do
          def permitted_params
            @permitted_params ||= declared(params, 
               include_missing: false)
          end

          def logger
            Rails.logger
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

app/controllers/api/v1/items.rb
module API
  module V1
    class Items < Grape::API
      include API::V1::Defaults
      resource :items do
        desc "Return all items"
        get "" do
          Item.all
        end
      desc "Return an item"
        params do
          requires :id, type: String, desc: "ID of the item"
        end
        get ":id" do
          Item.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/api/v1/recipes.rb
module API
  module V1
    class Recipes < Grape::API
      include API::V1::Defaults
      resource :recipes do
        desc "Return all items"
        get "" do
          Recipe.all
        end
      desc "Return an item"
        params do
          requires :id, type: String, desc: "ID of the item"
        end
        get ":id" do
          Recipe.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save!
    if @comment.save
        redirect_to items_path
      else
        redirect_to items_path
      end
  end

  def update
  end

  def destroy
  end

  def index
  end

  def new
    @comment = Comment.new
    @item = Item.find(params["format"])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  end

  def index
    @items = Item.all.order(id: :asc)
    @item = Item.new
    
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def update
    @item.save
    if @item.save
        redirect_to items_path
      else
        render items_path
      end
  end

  def mark
    @item = Item.find(params[:id])
    @item.marked = !@item.marked
    @item.save
    redirect_to items_path
  end

  def delete_all_marked
    Item.where(marked: true).destroy_all
    redirect_to items_path
  end

  def delete_all
    Item.delete_all
    redirect_to items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.save
    if @item.save
        redirect_to items_path
      else
        render items_path
      end
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if current_user
      redirect_to items_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController

    def create
      @recipe_comment = RecipeComment.new(comment_params)
      @recipe_comment.save!
      if @recipe_comment.save
          redirect_to recipes_path
        else
          redirect_to recipes_path
        end
    end
  
    def update
    end
  
    def destroy
    end
  
    def index
    end
  
    def new
      @recipe_comment = RecipeComment.new
      @recipe = Recipe.find(params["format"])
    end
  
    private
  
    def comment_params
      params.require(:recipe_comment).permit(:content, :recipe_id)
    end
end
  

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(current: true).order(id: :asc)
    @recipe = Recipe.new
    @recipes_past = Recipe.where(current: false).order(name: :asc)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def update
  end

  # def toggle_current
  #   @recipe = Recipe.find(params[:id])
  #   @recipe.current = !@recipe.current
  #   @recipe.save
  #   redirect_to recipes_path
  # end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save
    if @recipe.save
        redirect_to recipes_path
      else
        render recipes_path
      end
  end

  def delete_all
    Recipe.all.each do |recipe|
      recipe.current = false
      recipe.save
    end
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def selected_recipe
    id = params[:id]
    @selected_recipe = Recipe.find(id: id)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h4>Add a new comment for <%= @item.name %></h4>
    <%= simple_form_for @comment do |f| %>
      <%= f.input :content, wrapper_html: { class: 'form-name' } %>
      <%= f.input :item_id, :as => :hidden, :input_html => { :value => @item.id } %>
      <%= f.button :submit, 'Add comment' , class: "btn btn-secondary" %>
    <% end %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/items/delete.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/delete_all.html.erb
<h1>Items#delete_all</h1>
<p>Find me in app/views/items/delete_all.html.erb</p>

app/views/items/delete_all_marked.html.erb
<h1>Items#delete_all_marked</h1>
<p>Find me in app/views/items/delete_all_marked.html.erb</p>

app/views/items/index.html.erb
<%= render 'shared/navbar' %>

<h1>Shopping list</h1>

<% if @items %>
  <ul class="list-group mb-3" id="items">
    <% counter = 1 %>
    <% @items.each do |item| %>
      <li class="list-group-item" data-id="<%= counter %>"><span class="
      <%= "item-marked" if item.marked %>
      "><%= item.name %> x <%= item.quantity %></span><br>
      <%= link_to item_path(item),
                  method: :delete,
                  item_id: item.id,
                  data: { confirm: "Are you sure you want to clear this item?" } do %>
          <i class="far fa-trash-alt"></i>
          <% end %>   
      <%= link_to mark_item_path(item),
                method: :mark,
                  item_id: item.id do %>
          <i class="fas fa-check-circle"></i>
          <% end %>
      <%= link_to new_comment_path(item.id),
                  query: "test" ,
                  item: item do %>
          <i class="far fa-comment"></i>
          <% end %>
      <% counter += 1 %>
      <% if item.comments.length > 0 %>
        <% item.comments.each do |comment| %>
          <p class="item-comment"><%= comment.content %></p>
        <% end %>
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to delete_all_marked_path,
                method: :delete_all_marked,
                data: { confirm: "Are you sure you want to clear all marked items?" } do %>
        <button class="btn btn-secondary">Clear all marked items</button>
<% end %>   

<%= link_to delete_all_path,
                method: :delete_all,
                data: { confirm: "Are you sure you want to clear all items?" } do %>
        <button class="btn btn-secondary">Clear all items</button>
<% end %>   


 <div class="p-3">
    <h4>Add a new item:</h4>
    <%= simple_form_for @item do |f| %>
      <%= f.input :name, wrapper_html: { class: 'form-name' } %>
      <%= f.input :quantity, wrapper_html: { class: 'form-quantity' }, input_html: { value: '1' } %>
      <%= f.button :submit, 'Add item' , class: "btn btn-secondary" %>
    <% end %>
  </div>

app/views/items/mark.html.erb
<h1>Items#mark</h1>
<p>Find me in app/views/items/mark.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%# <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/recipe_comments/new.html.erb
<h4>Add a new comment for <%= @recipe.name %></h4>
    <%= simple_form_for @recipe_comment do |f| %>
      <%= f.input :content, wrapper_html: { class: 'form-name' } %>
      <%= f.input :recipe_id, :as => :hidden, :input_html => { :value => @recipe.id } %>
      <%= f.button :submit, 'Add comment' , class: "btn btn-secondary" %>
    <% end %>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/index.html.erb
<%= render 'shared/navbar' %>

<h1>Recipes</h1>

<% if @recipes %>
  <% @recipes.each do |recipe| %>
    <h3><%= recipe.name %>
    <%= link_to recipe_path(recipe),
                method: :delete,
                item_id: recipe.id,
                data: { confirm: "Are you sure you want to clear this recipe?" } do %>
        <i class="far fa-trash-alt"></i>
        <% end %>
        <%= link_to new_recipe_comment_path(recipe.id),
                  query: "test" ,
                  recipe: recipe do %>
          <i class="far fa-comment"></i>
          <% end %>
      <% if recipe.recipe_comments.length > 0 %>
        <% recipe.recipe_comments.each do |comment| %>
          <p class="recipe-comment"><%= comment.content %></p>
          
        <% end %>
      <% end %>
    </h3>
  <% end %>
<% end %>

<%= link_to delete_all_recipes_path,
                method: :delete_all,
                data: { confirm: "Are you sure you want to clear all recipes?" } do %>
        <button class="btn btn-secondary">Clear all recipes</button>
<% end %>   


 <div class="p-3">
    <h4>Add a new meal:</h4>
    <%= simple_form_for @recipe do |f| %>
      <%= f.input :name, wrapper_html: { class: 'form-name' } %>
      <%= f.button :submit, 'Add recipe' , class: "btn btn-secondary" %>
    <% end %>
  </div>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="shopping-navbar">
  <%= link_to items_path do %>
    <div class="shopping-navbar-item-items"><h3>Shopping</h3></div>
  <% end %>
  <%= link_to recipes_path do %>
    <div class="shopping-navbar-item-recipes"><h3>Recipes</h3></div>
  <% end %>
</div>